dependencies:
   - name: nodejs
     version: ~1.0.0
     repository: '@hmctspublic'
   - name: redis
     version: 5.1.2
     repository: '@stable'
   - name: idam-pr
     version: ~1.0.0
     repository: '@hmctspublic'
     tags:
     - idam-pr