version: '2.1'

services:
  codecept:
    image: reform/codeceptjs:8
    command: /bin/true
    environment:
      E2E_FRONTEND_URL: ${E2E_FRONTEND_URL:-https://localhost:8080}
    network_mode: 'service:frontend'
    volumes:
      - "../.:/tests"

  frontend:
    build:
      context: ../.
      args:
        - NODE_ENV=development
        - http_proxy
        - https_proxy
        - no_proxy
        - GIT_REVISION
        - PUBLIC_HOSTNAME
    environment:
      NODE_ENV: development
      REDISCLOUD_URL: 'redis://redis:6379'
    image: divorce/frontend:${FRONTEND_TAG:-master}
    links:
      - redis
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "../.:/opt/app"
    command: ["yarn", "run", "start-debug"]
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 3
