version: '2.1'

services:
  codecept:
    image: reform/codeceptjs:8
    command: /bin/true
    environment:
      E2E_FRONTEND_URL: ${E2E_FRONTEND_URL:-https://localhost:8080}
    network_mode: 'service:frontend'
    volumes:
      - "../.:/tests"

  frontend:
    environment:
      - REDISCLOUD_URL=redis://redis:6379
      - NODE_ENV
      - DIVORCE_HTTP_PROXY=${http_proxy}
    image: divorce/frontend:${FRONTEND_TAG:-master}
    links:
      - redis
    expose:
      - "8080"
    volumes:
      - "../node_modules:/opt/app/node_modules"
    command: ["yarn", "run", "start-dev"]
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 3

