deployment_env: 'aat'

services:
  postcodeInfo:
    url: 'https://api.ordnancesurvey.co.uk/places/v1'
    token: 'c4cb22c098c24eda8ba0df7eaaae66ef'
  idamAuthentication:
    health: 'https://idam-web-public.aat.platform.hmcts.net/health'
  idamApp:
    health: 'https://idam-api.aat.platform.hmcts.net/health'
  serviceAuthProvider:
    baseUrl: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    health: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal/health'
    microserviceKey: '2eaea72ca1d74f5192bac27c963c490b'
  payment:
    baseUrl: 'http://payment-api-aat.service.core-compute-aat.internal'
    health: 'http://payment-api-aat.service.core-compute-aat.internal/health'
  transformation:
    baseUrl: 'http://div-cos-aat.service.core-compute-aat.internal'
    draftBaseUrl: 'http://div-cos-aat.service.core-compute-aat.internal/draftsapi/version/1'
    health: 'http://div-cos-aat.service.core-compute-aat.internal/health'
  feesAndPayments:
    baseUrl: 'http://div-fps-aat.service.core-compute-aat.internal'
    health: 'http://div-fps-aat.service.core-compute-aat.internal/health'

features:
  idam: true
  strategicPay: true

idamArgs:
  redirectUri: 'https://localhost:3000/authenticated'
  idamApiUrl: 'https://idam-api.aat.platform.hmcts.net'
  idamLoginUrl: 'https://idam-web-public.aat.platform.hmcts.net/login'
  idamSecret: '170aba568e004b4ea2021b6124ce4f2e''

evidenceManagmentClient:
  url: 'http://div-emca-aat.service.core-compute-aat.internal'
  health: 'http://div-emca-aat.service.core-compute-aat.internal/health'


secret: 'cc145270f8cc458497814e6f516b0a31'
sessionEncryptionSecret: # Defined by SESSION_ENCRYPTION_SECRET in env

featureToggles:
  launchDarklyKey: # Defined by LAUNCHDARKLY_KEY in env

testUser:
  idamCitizenEmail: # Defined by idam citizen username
  idamCitizenPassword: # Defined by idam citizen password
