# make a copy of this as local-testing.yaml  (which should be git ignored) and add any local testing specific stuff

features:
  idam: false
  release510: true
  release520: true
  release520Desertion: true
  release530: true
