deployment_env: 'aat'

services:
  postcodeInfo:
    url: 'https://api.os.uk/search/places/v1'
    token: # Defined by POST_CODE_ACCESS_TOKEN in env
  idamAuthentication:
    health: 'https://idam-web-public.aat.platform.hmcts.net/health'
  idamApp:
    health: 'https://idam-api.aat.platform.hmcts.net/health'
  serviceAuthProvider:
    baseUrl: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    health: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal/health'
    microserviceKey: # Microservice key should be defined as MICROSERVICE_KEY in env

  payment:
    baseUrl: 'http://payment-api-aat.service.core-compute-aat.internal'
    health: 'http://payment-api-aat.service.core-compute-aat.internal/health'
  transformation:
    baseUrl: 'http://div-cos-aat.service.core-compute-aat.internal'
    draftBaseUrl: 'http://div-cos-aat.service.core-compute-aat.internal/draftsapi/version/1'
    health: 'http://div-cos-aat.service.core-compute-aat.internal/health'
  feesAndPayments:
    baseUrl: 'http://div-fps-aat.service.core-compute-aat.internal'
    health: 'http://div-fps-aat.service.core-compute-aat.internal/health'

features:
  idam: true
  strategicPay: true

idamArgs:
  redirectUri: 'https://localhost:3000/authenticated'
  idamApiUrl: 'https://idam-api.aat.platform.hmcts.net'
  idamLoginUrl: 'https://idam-web-public.aat.platform.hmcts.net/login'
  idamSecret: # Defined by IDAM_SECRET in env

evidenceManagementClient:
  url: 'http://div-emca-aat.service.core-compute-aat.internal'
  health: 'http://div-emca-aat.service.core-compute-aat.internal/health'


secret: # Defined by SECRET in env
sessionEncryptionSecret: # Defined by SESSION_ENCRYPTION_SECRET in env

featureToggles:
  launchDarklyKey: # Defined by LAUNCHDARKLY_KEY in env

testUser:
  idamCitizenEmail: # Defined by idam citizen username
  idamCitizenPassword: # Defined by idam citizen password
