env = "demo"
vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
service_auth_provider_url = "https://preprod-s2s-api.reform.hmcts.net:3511"
idam_authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
fee_register_url = "https://preprod.fees-register.reform.hmcts.net:4411"
payments_api_url = "https://preprod.payments.reform.hmcts.net:4401"
ga_tracking_id = "UA-93824767-1"
