vault_section = "prod"
idam_api_url = "https://prod-idamapi.reform.hmcts.net:3511"
service_auth_provider_url = "https://prod-s2s-api.reform.hmcts.net:3511"
idam_authentication_web_url = "https://www.idam.reform.hmcts.net"
fee_register_url = "https://fees-register.reform.hmcts.net:4411"
payments_api_url = "https://payments.reform.hmcts.net:4401"
ga_tracking_id = "UA-93824767-3"
